docs(hashgraph): initial draft
topology-foundation/docs-topology pull request #7
Opened 2024-10-29 09:02 UTC by h3lio5

2024-10-30 06:06 UTC, guiltygyoza requested changes
requested changes / reconsiderations

2024-10-30 06:06 UTC, guiltygyoza commented on docs/get-started/hashgraph.md
> +![Hash graph of a CRO](/img/hash_graph.png)
let's make our own drawings

2024-10-30 06:06 UTC, guiltygyoza commented on docs/get-started/hashgraph.md
> +Notably, this approach is immune to sybil attacks, allowing CROs to tolerate many sybil actors in the network.
we'll need to explain this in much simpler terms while being precise. "many sybil actors" so precisely how many? are we still subject to the f / 3f+1 limitation?

2024-10-30 06:06 UTC, guiltygyoza commented on docs/get-started/hashgraph.md
> +2. **Deterministic Conflict Resolution**: When concurrent operations occur, the CRO's conflict resolution rules ensure that all replicas resolve conflicts in exactly the same way, regardless of the o
don't introduce it here yet. "conflict" is introduced in the next section. it's a new term for most devs

2024-10-30 06:18 UTC, h3lio5 commented on docs/get-started/hashgraph.md
> +2. **Deterministic Conflict Resolution**: When concurrent operations occur, the CRO's conflict resolution rules ensure that all replicas resolve conflicts in exactly the same way, regardless of the o
can I make `Deterministic Conflict Resolution` embed a hyperlink to the conflicts page? Wanted to keep conflicts here just for sake of completeness of explaining how eventual consistency is guaranteed.

2024-10-30 06:18 UTC, h3lio5 commented on docs/get-started/hashgraph.md
> +![Hash graph of a CRO](/img/hash_graph.png)
ok, but i took this from our whitepaper. Perhaps you meant the hash graph image?

2024-10-30 07:05 UTC, h3lio5 commented on docs/get-started/hashgraph.md
> +Notably, this approach is immune to sybil attacks, allowing CROs to tolerate many sybil actors in the network.
i think it's better to leave out this detail until the finality design is complete? Don't think we can be super precise about bft rn.

2024-11-01 05:45 UTC, guiltygyoza requested changes
requested changes

2024-11-01 05:45 UTC, guiltygyoza commented on docs/get-started/hashgraph.md
> +When two nodes synchronize their operation histories of the same CRO, they effectively merge their hash graphs. The merge operation performs the union of hashgraphs. Merging might require resolving c
Merging does not require resolving concurrent operations

2024-11-01 05:45 UTC, guiltygyoza commented on docs/get-started/hashgraph.md
> +When two nodes synchronize their operation histories of the same CRO, they effectively merge their hash graphs. The merge operation performs the union of hashgraphs. Merging might require resolving c
also it's much clearer to add a short paragraph explaining the following graph

2024-11-01 05:45 UTC, guiltygyoza commented on docs/get-started/hashgraph.md
> +Notably, this approach is immune to sybil attacks, allowing CROs to tolerate many sybil actors in the network.
yes we can. see https://arxiv.org/pdf/2012.00472 figure 1

2024-11-01 05:45 UTC, guiltygyoza commented on docs/get-started/hashgraph.md
> +Notably, this approach is immune to sybil attacks, allowing CROs to tolerate many sybil actors in the network.
we don't have finality in the protocol yet. but hashgraph already provides certain bft properties and it's important to explain what's provided

2024-11-01 05:45 UTC, guiltygyoza commented on docs/get-started/hashgraph.md
> +2. **Deterministic Conflict Resolution**: When concurrent operations occur, the CRO's conflict resolution rules ensure that all replicas resolve conflicts in exactly the same way, regardless of the o
yes ofc

2024-11-05 04:55 UTC, guiltygyoza approved these changes
the sybil resistant part needs clarification, to be done in a separate PR. lgtm

2024-11-05 04:55 UTC, merged